<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DERIW42SLPC1327" name="com.tricentis.automation.scripts.fieldVerification.HomePageTests" tests="5" failures="0" timestamp="04 Apr 2020 12:31:51 GMT" time="250.117" errors="1">
  <testcase name="verifyTrucklink" time="0.032" classname="com.tricentis.automation.scripts.fieldVerification.HomePageTests"/>
  <testcase name="verifyCamperlink" time="0.036" classname="com.tricentis.automation.scripts.fieldVerification.HomePageTests"/>
  <testcase name="teardown" time="199.399" classname="com.tricentis.automation.scripts.fieldVerification.HomePageTests">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerExceptionat com.tricentis.automation.libraries.ZipUtility.zipIt(ZipUtility.java:50)at com.tricentis.automation.libraries.ZipUtility.zipReport(ZipUtility.java:24)at com.tricentis.automation.driver.Driver.teardown(Driver.java:74)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- teardown -->
  <testcase name="verifyAutomationlink" time="50.634" classname="com.tricentis.automation.scripts.fieldVerification.HomePageTests"/>
  <testcase name="verifyMotorCyclelink" time="0.016" classname="com.tricentis.automation.scripts.fieldVerification.HomePageTests"/>
</testsuite> <!-- com.tricentis.automation.scripts.fieldVerification.HomePageTests -->
